services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_manager_test
    ports:
      - "55432:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_test: